version: '3'

services:
  elk:
    image: sebp/elk:7.16.1
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
     - elk
    container_name: elk
    volumes:
#      - ./config/elasticsearch/:/etc/elasticsearch/:rw
      - ./config/logstash/conf.d/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf:rw
      - ./elk-data:/var/lib/elasticsearch:rw
    restart: always
networks:
  elk:
    driver: bridge