server:
  port: 30000
  error:
    include-message: always

spring:
  redis:
    database: 0
    host: 192.168.253.130
    port: 6379
    password: 123456
    # 连接超时时间
    timeout: 10000
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.253.130:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        cluster-name: Cluster-A
        namespace: dev
        group: DEFAULT_GROUP
        register-enabled: true
        watch:
          enabled: true
        watch-delay: 30000
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
#      routes:
#        - id: id-0012
#          uri: lb://coupon-customer-serv
#          predicates:
#            - Path=/whatever/**
#          filters:
#            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            # 授信地址列表
            allowed-origins:
              - "http://localhost:10000"
              - "https://www.baidu.com"
            # cookie, authorization认证信息
            exposed-headers: "*"
            allowed-methods: "*"
            allow-credentials: true
            allowed-headers: "*"
#        add-to-simple-url-handler-mapping: true
  sleuth:
    sampler:
      probability: 1
      rate: 1000


management:
  endpoints:
    web:
      exposure:
        include: "*"


#logging:
#  level: debug