version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    env_file:
      - .env
    environment:
      - STORAGE_TYPE=mem
      # Point the zipkin at the storage backend
#      - MYSQL_HOST=mysql
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - "9411:9411"
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
#    depends_on:
#      - storage
    restart: always
    networks:
      - net1
  zipkin-ui:
    image: openzipkin/zipkin-ui
    container_name: zipkin-ui
    environment:
      # Change this if connecting to a different zipkin server
      - ZIPKIN_BASE_URL=http://zipkin:9411
    ports:
      - "80:80"
    depends_on:
      - zipkin
    networks:
      - net1
    restart: always
networks:
  net1:
    driver: bridge